//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightningReturnFFXIII_pt_BR.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightningReturnFFXIII_pt_BR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tanto o programa quanto a tradução estão na versão mais recente..
        /// </summary>
        internal static string AllUpDate {
            get {
                return ResourceManager.GetString("AllUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fazendo download da atualização do programa!.
        /// </summary>
        internal static string AppUpdate {
            get {
                return ResourceManager.GetString("AppUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uma nova versão do programa está disponível.
        ///Você quer atualizar?.
        /// </summary>
        internal static string AppUpdateMessage {
            get {
                return ResourceManager.GetString("AppUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Versão do programa:  {0}.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a v{0}.
        /// </summary>
        internal static string AppVersionString {
            get {
                return ResourceManager.GetString("AppVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciando a instalação, não feche o programa.
        ///Se houver algum problema ou fechamento inesperado.
        ///Use \&quot;Desinstalar\&quot; e reinstale.
        ///Tradução gratuita feita pela TriboGamer.
        ///Faça o download do programa apenas em tribogamer.com para evitar a inserção de código malicioso..
        /// </summary>
        internal static string BeginInstall {
            get {
                return ResourceManager.GetString("BeginInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro: pacote de traduçao não encontrado.
        ///
        ///Atualize a tradução..
        /// </summary>
        internal static string BinNotFounded {
            get {
                return ResourceManager.GetString("BinNotFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tem um processo em andamento.
        ///Se interromper, pode corromper os arquivos do jogo..
        /// </summary>
        internal static string CancelWarning {
            get {
                return ResourceManager.GetString("CancelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tem certeza?.
        /// </summary>
        internal static string ConfirmAnswer {
            get {
                return ResourceManager.GetString("ConfirmAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fazendo download da tradução....
        /// </summary>
        internal static string DownTranslation {
            get {
                return ResourceManager.GetString("DownTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Download do pacote de tradução finalizado!.
        /// </summary>
        internal static string DownTranslationComplete {
            get {
                return ResourceManager.GetString("DownTranslationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Extração do pacote de tradução foi interrompido.
        ///Id do pacote é diferente do Id da tradução..
        /// </summary>
        internal static string ExtractPackageInterrupted {
            get {
                return ResourceManager.GetString("ExtractPackageInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aviso:
        ///
        ///Para instalar a tradução, a unidade precisa ter cerca de 5 GB livres.
        ///Sua unidade tem {0} de espaço livre. Continuar?.
        /// </summary>
        internal static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Como não pode ter diretório do jogo?.
        /// </summary>
        internal static string GameDirectoryNot {
            get {
                return ResourceManager.GetString("GameDirectoryNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LIGHTNING RETURNS FINAL FANTASY XIII.
        /// </summary>
        internal static string GameLocation {
            get {
                return ResourceManager.GetString("GameLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você está conectado à internet?.
        /// </summary>
        internal static string HttpRequestBroken {
            get {
                return ResourceManager.GetString("HttpRequestBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro: Outro processo em andamento.
        ///
        ///Aguarde..
        /// </summary>
        internal static string InProgressWarning {
            get {
                return ResourceManager.GetString("InProgressWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instalação interrompida!!!.
        /// </summary>
        internal static string InstallBroken {
            get {
                return ResourceManager.GetString("InstallBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instalação da tradução cancelada..
        /// </summary>
        internal static string InstallCanceled {
            get {
                return ResourceManager.GetString("InstallCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instalação da tradução está completa..
        /// </summary>
        internal static string InstallTranslationComplete {
            get {
                return ResourceManager.GetString("InstallTranslationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro: pasta do jogo não encontrada.
        ///
        ///Selecione a pasta correta do jogo..
        /// </summary>
        internal static string LocationException {
            get {
                return ResourceManager.GetString("LocationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LR13 {
            get {
                object obj = ResourceManager.GetObject("LR13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fazendo cópia de segurança.
        /// </summary>
        internal static string MakeBackup {
            get {
                return ResourceManager.GetString("MakeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro: O arquivo não pôde ser lido.
        ///É possível que você esteja instalando em um diretório ao qual o programa não tem permissão de acesso.
        ///Verifique o diretório ou execute o programa como Admin..
        /// </summary>
        internal static string ReadFailed {
            get {
                return ResourceManager.GetString("ReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obtendo informações do servidor.
        /// </summary>
        internal static string Server_Response {
            get {
                return ResourceManager.GetString("Server_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Id da tradução: {0}.
        /// </summary>
        internal static string TranslationID {
            get {
                return ResourceManager.GetString("TranslationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data da tradução: {0}..
        /// </summary>
        internal static string TranslationTime {
            get {
                return ResourceManager.GetString("TranslationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Uma nova versão da tradução está disponível.
        ///Deseja atualizar?.
        /// </summary>
        internal static string TranslationUpdateMessage {
            get {
                return ResourceManager.GetString("TranslationUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desinstalação completa..
        /// </summary>
        internal static string UninstallComplete {
            get {
                return ResourceManager.GetString("UninstallComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tem certeza que quer desinstalar?.
        /// </summary>
        internal static string UninstallConfirm {
            get {
                return ResourceManager.GetString("UninstallConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha na desinstalação!
        ///
        ///É possível que o LRFF13 tenha sido desinstalado ou, durante a desinstalação foi interrompido inesperadamente..
        /// </summary>
        internal static string UninstallFailed {
            get {
                return ResourceManager.GetString("UninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Iniciando a desinstalação, não feche o programa..
        /// </summary>
        internal static string UninstallStart {
            get {
                return ResourceManager.GetString("UninstallStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desinstalação interrompida!!!.
        /// </summary>
        internal static string UnistallBroken {
            get {
                return ResourceManager.GetString("UnistallBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualização interrompida!!!.
        /// </summary>
        internal static string UpdateBroken {
            get {
                return ResourceManager.GetString("UpdateBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro: O arquivo não pôde ser gravado.
        ///Você pode estar instalando no diretório somente leitura ou o programa não tem permissões.
        ///Verifique o diretório ou execute o programa abaixo. Direitos de administrador..
        /// </summary>
        internal static string WriteFailed {
            get {
                return ResourceManager.GetString("WriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este não é um pacote de tradução para LRFFXIII..
        /// </summary>
        internal static string WrongPackage {
            get {
                return ResourceManager.GetString("WrongPackage", resourceCulture);
            }
        }
    }
}
